### ISSUE TITLE
Need Better Logo/Art

### ISSUE THREAD

**Issue by petabyt** [Pufflegamerz/ScratchFormat#3]
Current logo:  
![logo2](https://user-images.githubusercontent.com/32369330/33585568-e9a8474a-d932-11e7-9b64-b7727c091a70.png)

**Comment by petabyt** [comment]
Need one that looks better when it's smaller. If anybody has the time...

**Comment by radioblahaj** [comment]
hi

**Comment by radioblahaj** [comment]
need Help?

**Comment by petabyt** [comment]
yes
